### ISSUE TITLE
有mongo的脚本吗？

### ISSUE THREAD

**Issue by xrogzu** [fengzhizi715/ProxyPool#1]
您好，有mongo的集合脚本吗？跑起来报错，谢谢

**Comment by sinkinka** [comment]
您好，建一个数据库： proxypool
然后，collection分别是：Proxy_Resource、Resource_Plan、Proxy、Sys_Sequence、Job_Log

**Comment by fengzhizi715** [comment]
@xrogzu 报什么错？

**Comment by morrislchg** [comment]
Sys_Sequence要添加一条数据

**Comment by xrogzu** [comment]
@fengzhizi715 找不到集合，空指针错误

**Comment by sinkinka** [comment]
@xrogzu  您好！ 请在  Sys_Sequence中添加一条数据。

{
    "colName" : "Proxy_Resource",
    "sequence" : 1
}

sequence的值只要是自然数就可以
