### ISSUE TITLE
实时代理服务器列表是挂了吗？

### ISSUE THREAD

**Issue by fa-ge** [fengzhizi715/ProxyPool#4]
http://47.97.7.119:8080/proxypool/proxylist  只有两个有效的啦

**Comment by derekhe** [comment]
看来已经凉了，请参考我的这本书教你做代理池：https://item.jd.com/12575102.html

**Comment by fengzhizi715** [comment]
hi @derekhe  在别人的地方放广告不太妥吧？

**Comment by derekhe** [comment]
> hi @derekhe 在别人的地方放广告不太妥吧？

算了，删除了免得误解。
